# apiVersion: v1
# kind: Pod
# metadata:
#   name: multi-containers-1
# spec:
#   containers:
#   - name: nginx
#     image: nginx
#     ports:
#     - containerport: 80
#   - name: almalinux
#     image: almalinux:8
#     command: ["sleep", "300"]

apiVersion: v1
kind: Pod
metadata:
  name: multi-container-1
spec:
  # list of containers
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
  - name: almalinux
    image: almalinux:8
    command: ["sleep", "300"]
