apiVersion: v1
kind: Pod
metadata:
  name: multi-containers-1
spec:
  containers:
  - name: pod-1
    image: nginx
    ports:
    - containerport: 80
  - name: pod-2
    image: almalinux
    command: ["sleep", "300"]
