apiVersion: v1
kind: Pod
metadata:
  name: labels
  labels:
    course: Devops
    Trainer: "Sivakumar" 
spec:
  # list of containers
  containers:
  - name: hello-pod
    image: nginx
    #here with this line port will not be opened, just for information
    ports:
    - containerPort: 80